name: kars_driver_app
description: Application for Driver Kars
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  curl_logger_dio_interceptor: ^1.0.0
  device_info_plus: ^12.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  event_bus: ^2.0.1
  extended_image: ^10.0.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  flutter_timezone: ^5.0.1
  fluttertoast: ^8.2.12
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  logger: ^2.6.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_dio_logger: ^1.4.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  stream_transform: ^2.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
  fonts:
    enabled: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - environment.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
